version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
    - 27017:27017
    restart: always
    container_name: practica6-bootcamp
    hostname: hostmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    
  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MOMGODB_PORT: 27017  
